DATA SEGMENT
STRING DB "I LOVE MAYDAY AND FRIDAY!$"
MESS   DB 0AH,0DH,"INPUT A WORD:$"
MESS2  DB 0AH,0DH,"THE POSITION IS:$"
NO     DB 0AH,0DH,"NOT FOUND.$"
X      DB ?
C10    DB 10
POSITION DB -1
DATA ENDS
CODE SEGMENT
	ASSUME CS:CODE,DS:DATA
START:
	MOV AX,DATA
	MOV DS,AX
	MOV ES,AX;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;！！！！！
	LEA DX,STRING
	 MOV AH,09H
	INT 21H
	LEA DX,MESS
	 MOV AH,09H
	INT 21H
	MOV AH,01
	INT 21H
	MOV X,AL
	MOV AL,X
	LEA DI,STRING
	MOV CX,25
	CLD
	REPNZ SCASB
	JZ  YES
	LEA DX,NO
	MOV AH,09H
	INT 21H
	JMP EXIT

YES:	MOV AL,25
	SUB AL,CL;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;影响标志位的判断
	MOV POSITION,AL
	LEA DX,MESS2
	MOV AH,09H
	INT 21H
	MOV CX,2
	MOV AL,POSITION
ONE:	MOV AH,0
	DIV C10
	PUSH AX
	LOOP ONE
	MOV CX,2
TWO:	POP DX
	XCHG DH,DL
	OR DL,30H
	MOV AH,2
	INT 21H
	LOOP TWO	
EXIT:	MOV  AX,4C00H
	INT 21H
	
CODE ENDS 
	END START