DATA		SEGMENT
	X	DW  	55, 112, 37, 82
	Y	DW  	4 DUP (?)
DATA		ENDS
CODE		SEGMENT
ASSUME	CS: CODE, DS: DATA
START:MOV  AX, DATA
	MOV	DS, AX
	MOV	DI, 4		
	MOV	AX, X[DI]	
	MOV	Y[DI], AX	
	MOV	AX, X[DI+2]	
	MOV	Y[DI+2], AX	
	MOV	AX, 4C00H
	INT  	21H
CODE		ENDS
	END	START
